name: MoonTVPlus Trigger on Push
on:
  push:
    branches:
      - main  # 当 main 分支有更新时触发
  workflow_dispatch: # 允许手动点击按钮触发
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cron API
        run: |
          curl -X GET "https://tv.0121314.xyz/api/cron/mtvpls" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
